Feature: Creating Business Account


  @Regression
  Scenario Outline: Creating Business Account for <brandName>
    Given I launch '<brandName>' Business Onboarding & Account Opening application
    When I login with '<credentials>' to the application and navigate to homepage
    And  I start New application for partenrship and enter '<personalDetails>','<organizationDetails>','<businessDetails>','<businessfinancials>','<teamDetails>','<teamDetailsAnotherMember>'and'<manageAccounts>'information
    Then I should get navigate reviewapplication page
    Examples:
      | brandName | credentials                       | personalDetails  | organizationDetails                      | businessDetails              | businessfinancials                                                                                                                                                                                                                 | teamDetails                                                                                       | teamDetailsAnotherMember                                                                                                                  | manageAccounts                                                                                                                                                               |
  #     | RBS       | peppinfernando@gmail.com,Rose!234 | MR,Peppin,Walter | Yes,Partnership - General Partnership    | Reya Tours1,No,77C,BR1 3AA,No | 160000,March,2018,December,5,Tour,AllTransferNoCash,United Kingdom,sessionalbusinessNo,intTradeNo,United Kingdom,paytaxoutsideukNO,existingbusrelationshipNo,SwitchYourBusinessAccountToUsNo,MoneyComingInNo | 10,July,1983,+44,Male,United Kingdom,Bromley,personalaccountNo,June,2016,PayTaxOutUKNo,United Kingdom,77 C,BR1 3AA,50,50| MR,Shankar,Gajangi,11,July,1988,+44,Male,United Kingdom,Glasgow,personalaccountNo,June,2016,PayTaxOutUKNo,United Kingdom,77 C,BR1 3AA,50,50|checkPaperStatementsNo,Monthly,checkPayingInBookYes,checkChequeBookYes,radioAdditionalAccNo,Overdraft-AcceptPaymentsFromYourCustomers-FreeAgentCloudBasedAccountancySoftware,One Signatory,limitOnMoneyNo,createGroupYes,infoNo |
 #     | Ulster    | peppinfernando@gmail.com,Rose!234 | MR,Peppin,Walter | Yes,Partnership - General Partnership    | Reya Tours1,No,77C,BR1 3AA,No | 160000,March,2018,December,5,Tour,AllTransferNoCash,United Kingdom,sessionalbusinessNo,intTradeNo,United Kingdom,paytaxoutsideukNO,existingbusrelationshipNo,SwitchYourBusinessAccountToUsNo,MoneyComingInNo | 10,July,1983,+44,Male,United Kingdom,Bromley,personalaccountNo,June,2016,PayTaxOutUKNo,United Kingdom,77 C,BR1 3AA,50,50| MR,Shankar,Gajangi,11,July,1988,+44,Male,United Kingdom,Glasgow,personalaccountNo,June,2016,PayTaxOutUKNo,United Kingdom,77 C,BR1 3AA,50,50|checkPaperStatementsNo,Monthly,checkPayingInBookYes,checkChequeBookYes,radioAdditionalAccNo,Overdraft-AcceptPaymentsFromYourCustomers-FreeAgentCloudBasedAccountancySoftware,One Signatory,limitOnMoneyNo,createGroupYes,infoNo |
      | NatWest   | peppinfernando@gmail.com,Rose!234 | MR,Peppin,Walter | Yes,Partnership - General Partnership    | Reya Tours1,No,77C,BR1 3AA,No | 160000,March,2018,December,5,Tour,AllTransferNoCash,United Kingdom,sessionalbusinessNo,intTradeNo,United Kingdom,paytaxoutsideukNO,existingbusrelationshipNo,SwitchYourBusinessAccountToUsNo,MoneyComingInNo | 10,July,1983,+44,Male,United Kingdom,Bromley,personalaccountNo,June,2016,PayTaxOutUKNo,United Kingdom,77 C,BR1 3AA,50,50| MR,Shankar,Gajangi,11,July,1988,+44,Male,United Kingdom,Glasgow,personalaccountNo,June,2016,PayTaxOutUKNo,United Kingdom,77 C,BR1 3AA,50,50|checkPaperStatementsNo,Monthly,checkPayingInBookYes,checkChequeBookYes,radioAdditionalAccNo,Overdraft-AcceptPaymentsFromYourCustomers-FreeAgentCloudBasedAccountancySoftware,One Signatory,limitOnMoneyNo,createGroupYes,infoNo |
